'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bancos
    Public Property ban_id As Integer
    Public Property ban_descripcion As String

    Public Overridable Property cuentascliente As ICollection(Of cuentascliente) = New HashSet(Of cuentascliente)

End Class
