'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categoria
    Public Property cant_id As Integer
    Public Property cat_descripcion As String
    Public Property cat_idestado As String
    Public Property cat_foto As String

    Public Overridable Property subcategoria As ICollection(Of subcategoria) = New HashSet(Of subcategoria)
    Public Overridable Property tienda As ICollection(Of tienda) = New HashSet(Of tienda)

End Class
