'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cuentascliente
    Public Property misc_id As Integer
    Public Property misc_idcliente As Nullable(Of Integer)
    Public Property misc_idbanco As Nullable(Of Integer)
    Public Property misc_idtipocuenta As Nullable(Of Integer)

    Public Overridable Property bancos As bancos
    Public Overridable Property cliente As cliente
    Public Overridable Property tipocuenta As tipocuenta

End Class
