'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class estadoorden
    Public Property esor_id As Integer
    Public Property esor_id_descripcion As String

    Public Overridable Property ordenes As ICollection(Of ordenes) = New HashSet(Of ordenes)

End Class
