'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mediopago
    Public Property Mep_id As Integer
    Public Property mep_descripcion As String
    Public Property mep_detalle As String
    Public Property mep_foto As String

    Public Overridable Property ordenes As ICollection(Of ordenes) = New HashSet(Of ordenes)

End Class
