'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class JosephTutos_PedidosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=JosephTutos_PedidosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property bancos() As DbSet(Of bancos)
    Public Overridable Property categoria() As DbSet(Of categoria)
    Public Overridable Property cliente() As DbSet(Of cliente)
    Public Overridable Property cuentascliente() As DbSet(Of cuentascliente)
    Public Overridable Property estadoorden() As DbSet(Of estadoorden)
    Public Overridable Property mediopago() As DbSet(Of mediopago)
    Public Overridable Property ordendetalle() As DbSet(Of ordendetalle)
    Public Overridable Property ordenes() As DbSet(Of ordenes)
    Public Overridable Property producto() As DbSet(Of producto)
    Public Overridable Property subcategoria() As DbSet(Of subcategoria)
    Public Overridable Property tienda() As DbSet(Of tienda)
    Public Overridable Property tipocuenta() As DbSet(Of tipocuenta)

    Public Overridable Function SP_Clientes(idCliente As String) As ObjectResult(Of SP_Clientes_Result)
        Dim idClienteParameter As ObjectParameter = If(idCliente IsNot Nothing, New ObjectParameter("idCliente", idCliente), New ObjectParameter("idCliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SP_Clientes_Result)("SP_Clientes", idClienteParameter)
    End Function

End Class
