'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ordenes
    Public Property ord_id As Integer
    Public Property ord_numero As String
    Public Property ord_idcliente As Nullable(Of Integer)
    Public Property ord_idtienda As Nullable(Of Integer)
    Public Property ord_direccion As String
    Public Property ord_fecha As String
    Public Property ord_latitud As String
    Public Property ord_longitud As String
    Public Property ord_altura As String
    Public Property ord_fechaenvio As String
    Public Property ord_idestado As Nullable(Of Integer)
    Public Property ord_totalcompra As Nullable(Of Double)
    Public Property ord_descripcion As String
    Public Property ord_idformapago As Nullable(Of Integer)
    Public Property detord_pagacon As String

    Public Overridable Property cliente As cliente
    Public Overridable Property estadoorden As estadoorden
    Public Overridable Property mediopago As mediopago
    Public Overridable Property ordendetalle As ICollection(Of ordendetalle) = New HashSet(Of ordendetalle)
    Public Overridable Property tienda As tienda

End Class
