'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property prod_id As Integer
    Public Property prod_codigo As String
    Public Property prod_nombre As String
    Public Property prod_descripcion As String
    Public Property prod_precioanterior As Nullable(Of Double)
    Public Property prod_preciounitario As Nullable(Of Double)
    Public Property prod_idcategoria As Nullable(Of Integer)
    Public Property prod_foto As String
    Public Property prod_color As String
    Public Property prod_ranking As String
    Public Property prod_stockmin As Nullable(Of Integer)
    Public Property prod_stok As Nullable(Of Integer)
    Public Property prod_stokmax As Nullable(Of Integer)
    Public Property prod_calificacion As Nullable(Of Double)
    Public Property prod_fecha As String
    Public Property prod_countventas As String
    Public Property prod_favorito As Nullable(Of Boolean)
    Public Property prod_descuento As Nullable(Of Double)
    Public Property prod_idtienda As Nullable(Of Integer)

    Public Overridable Property ordendetalle As ICollection(Of ordendetalle) = New HashSet(Of ordendetalle)
    Public Overridable Property subcategoria As subcategoria
    Public Overridable Property tienda As tienda

End Class
