'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tienda
    Public Property tien_id As Integer
    Public Property tien_nit As String
    Public Property tien_clave As String
    Public Property tien_tipoidentificacion As String
    Public Property tien_razonsocial As String
    Public Property tien_direccion As String
    Public Property tien_barrio As String
    Public Property tien_telefono As String
    Public Property tien_correo As String
    Public Property tien_latitud As String
    Public Property tien_longitud As String
    Public Property tien_altura As String
    Public Property tien_facebook As String
    Public Property tien_instagram As String
    Public Property tien_youtube As String
    Public Property tien_foto As String
    Public Property tien_premium As Nullable(Of Boolean)
    Public Property tien_key As String
    Public Property tien_privatekey As String
    Public Property tien_pkey As String
    Public Property tien_idcliente As String

    Public Overridable Property ordenes As ICollection(Of ordenes) = New HashSet(Of ordenes)
    Public Overridable Property producto As ICollection(Of producto) = New HashSet(Of producto)
    Public Overridable Property categoria As ICollection(Of categoria) = New HashSet(Of categoria)

End Class
